#!/usr/bin/env tsx

// More generic version of ./tstest.ts which imports the external declaration
// of types for a sample database, generated by ./typegen.ts.  The
// ColumnsForTableMethod utility type has been extended to allow the
// MusicDatabase specific type to be passed as the first generic Model
// parameter
import { MusicDatabase } from '../tmp/musicDatabase'

type TableMethod = 'select' | 'insert' | 'update' | 'delete'
type AnyTable = Record<TableMethod, AnyTableColumns>
type AnyTableColumns = Record<string, any>
type AnyDatabase = {
  tables: Record<string, AnyTable>
}
type ColumnsForTableMethod<
  Model extends AnyDatabase,
  TableName extends keyof Model['tables'],
  Method extends TableMethod
> =
  Model['tables'][TableName][Method]


function database<Model extends AnyDatabase>() {
  function table<Name extends keyof Model['tables']>(
    name: Name
  ) {
    return {
      insert: function(
        setColumns: ColumnsForTableMethod<Model, Name, 'insert'>,
      ) {
        return 'Fake insert'
      },
      update: function(
        setColumns: ColumnsForTableMethod<Model, Name, 'update'>,
        whereColumns: ColumnsForTableMethod<Model, Name, 'select'>
      ) {
        return 'Fake update'
      },
      select: function(
        whereColumns: ColumnsForTableMethod<Model, Name, 'select'>
      ) {
        return 'Fake select'
      },
      'delete': function(
        whereColumns: ColumnsForTableMethod<Model, Name, 'delete'>,
      ) {
        return 'Fake delete'
      },
    }
  }
  return { table }
}

const db = database<MusicDatabase>()

const artists = db.table('artists')
const response1 = artists.insert({ id: 11, name: 'Spinal Tap', volume: 11 })
const response2 = artists.update({ name: 'Spin̈al Tap' }, { id: 11 })
const response3 = artists.select({ id: 11 })
const response4 = artists.select({ volume: 11 })
const response5 = artists.delete({ id: 11 })

